### ISSUE TITLE
Seems tink_cli does not compile with last tink_io (but works with tink_io:0.5.0)

### ISSUE THREAD

**Issue by emugel** [haxetink/tink_cli#12]
Not sure if a bug, or whether I don't understand best practices, but I get the following error if not specifying "tink_io:0.5.0" in my hxml:

```/usr/share/haxelib/tink_cli/0,3,1/src/tink/cli/prompt/SimplePrompt.hx:5: characters 7-21 : Type not found : tink.io.Duplex```

If replacing `-l tink_io` with `-l tink_io:0.5.0` it compiles.
I am just installing libs with `sudo haxelib install tink_xxx` and using `sudo haxelib update` to update them.

Is there a documentation that deals about best practices to use tink libs? I use them more and more (as the tink libs are awesome, despite the learning curve). 

I also had the same problem where I had to use tink_core:1.17.1 instead of the latest to be able to use the latest tink_streams. 

I'm worried about situations where things would compile but code would be broken if forcing versions too much...

**Comment by kevinresol** [comment]
Please try again with latest haxelib versions.
