### ISSUE TITLE
GetDoc errors

### ISSUE THREAD

**Issue by melMass** [haxetink/tink_cli#16]
Hi,

Thanks for this library, exactly what I was about to write :).

I have a few issues I'm not sure if it's user error or code issues yet.

Here my simple case:

```haxe
class Go {
    public static function main() {
	Cli.process(Sys.args(), new GoCli()).handle(Cli.exit);
   }
}

class GoCli {

    @:flag('verbose')
    public static var debug:Bool;

    @:flag('-r')
    public static var targetSize:String;

    @:flag('help')
    public static var help:Bool;

    @:defaultCommand
    public function run(rest:Rest<String>) {
        if (help){
            trace(Cli.getDoc(run));
	    return;
         }
       trace('Resize to: $targetSize');
       trace('Verbose: $debug');
   }

}
```

Very simple case to illustrate my issues. I had to **completely remove the getDoc as it fails with the following errors**:

```ruby
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/cli/Macro.hx:235: characters 14-19 : Uncaught exception assert
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/cli/Macro.hx:33: characters 15-31 : Called from here
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/Cli.hx:24: characters 13-60 : Called from here
src/tools/Cmft.hx:176: characters 23-38 : Called from here
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/cli/Macro.hx:425: characters 29-32 : Called from here
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/cli/Macro.hx:506: characters 4-31 : Called from here
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/cli/Macro.hx:411: characters 11-43 : Called from here
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/cli/Macro.hx:110: characters 16-42 : Called from here
C:\HaxeToolkit\haxe\lib\tink_cli/git/src/tink/cli/Macro.hx:23: characters 57-73 : Called from here
For function argument 'message'
```

And my other issue is **Int not being catch**:

|Command  | Output |
| ------------- | ------------- |
| cmd -v  or cmd --verbose | Resize to: `null` Verbose: `true` |
| cmd -r 2048  | Resize to: `null` Verbose: `false`   |

**Comment by kevinresol** [comment]
getDoc takes a command instance as argument, so you should write: `Cli.getDoc(this)`

For the other problem, please provide a self-contained example. http://sscce.org/

**Comment by melMass** [comment]
Thanks! I'm not sure how more contained you want it to be ? You are talking about providing an HXML ?

**Comment by kevinresol** [comment]
Your code won't compile, e.g. "log" is undeclared

**Comment by melMass** [comment]
Edited sorry

**Comment by kevinresol** [comment]
I will appreciate if you can actually try compile the example once.

**Comment by kevinresol** [comment]
For future reference: tink_cli does not support `static var` as flags
