### ISSUE TITLE
In tink_cli + hxcpp giving "On static platforms, null can't be used as basic type Bool`"

### ISSUE THREAD

**Issue by emugel** [haxetink/tink_cli#19]
I am getting this error about 30 times with tink_cli 0.5.0. 

`~/haxe/haxe_libraries/tink_cli/0.5.0/haxelib/src/tink/cli/Macro.hx|169 col 21 error| On static platforms, null can't be used as basic type Bool`

I have seen a mention in haxelib info tink_cli that 0.5.0 introduces a breaking change:  `2019-11-06 06:47:50 0.5.0 : [breaking] Vars without expression is treated as required flags` but I can not figure out what it is.

I should probably investigate further but my app has subcommands (e.g. myapp command subcommand args) so a lot of classes are using tink_cli, better ask advice before.

Edit: reverted to tink_cli 0.4.1 for now, it compiles alright.

**Comment by kevinresol** [comment]
That is an usual haxe error. You can have `null` assigned to variable of type `Bool`, 
you have two solutions:
1. `var bool:Null<Bool> = null;`
1. `var bool:Bool = true; // or false`

**Comment by emugel** [comment]
I'm late to respond.
I liked it when `public var verbose : Bool` defaulted to false because for an option it seems to be a nice default. 

On the other hand this helps clarifying (and remembering) what happens when you use `public var a : Array<String>`, that is, it is `null` and not `[]`. So I guess there's a little less magic thoughts in this way and that it is good. I close this since you answered and it is not a bug, thanks!
