### ISSUE TITLE
Custom Exceptions for unknown flags ?

### ISSUE THREAD

**Issue by melMass** [haxetink/tink_cli#21]
Hi Kevin,

I've been using tink_cli quite a lot and I'm amazed at the possibilities!

How can I catch exceptions for unknown flags?

For now, it simply outputs:

```
Unexpected Error, Unrecognized alias "-a"
```

**Comment by kevinresol** [comment]
You can pass a custom handler to the   .handle() call

**Comment by melMass** [comment]
Thanks !!
